### ISSUE TITLE
Error after first login, but not after restart of awesome

### ISSUE THREAD

**Issue by pyro57** [stefano-m/awesome-pulseaudio_widget#7]
Got a weird one for you.
When I first boot up and log into an awesome session I get the following error:

Error while loading the PulseAudio widget
/usr/share/lua5.3/dbus_proxy/_proxy.lua:283 failed to introspect object 'org.PulseAudio1'
error: GDBussError.org.freedesktop.DBus.Error.ServiceUnknown: The neame org.PulseAudio1 was not provided by any .service files
Code: SERVICE_UNKNOWN

but after I restart awesomewm it loads fine and not other errors occur... I'm super new (as in the last 2 days) to awesome, so if you need any other info I may need help knowing where to go to provide that info.
thanks in advance for your help.

**Comment by stefano-m** [comment]
Hello and thank you for your interest in the pulsaudio widget!

I am sorry you are having issues with pulseaudio, this issue seems similar to #6 and I suspect that for some reason your pulseaudio may be somehow slow to start its DBus service.

To verify that, you could run the following command from a terminal

```shell
dbus-send --session --dest=org.freedesktop.DBus --print-reply /org/freedesktop/DBus org.freedesktop.DBus.ListNames
```

if it prints something like (there will be likely more elements than in the example):

```
array [
    string "org.freedesktop.DBus"
    string "org.pulseaudio.Server"
    string "org.PulseAudio1"
]
```
then there may be an issue with the widget, otherwise it's likely an issue with your pulseaudio.

It may be useful to know what OS you are using, how you are starting awesome and the pulseaudio version.

If this is an OS-specific issue I am afraid I cannot be of much help though and would suggest that you look at your OS forum or something similar (e.g. reddit).

Thanks

**Comment by stefano-m** [comment]
Closing for lack of feedback.
